<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-PGLI7LE" failures="1" tests="5" name="testcases.TestScenarios" time="221.949" errors="0" timestamp="2021-07-29T17:21:42 IST" skipped="0">
  <testcase classname="testcases.TestScenarios" name="scenarioCheckOutProcess" time="58.071">
    <failure message="Assertion for number of items in cart failed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Assertion for number of items in cart failed
at extent.reports.MyAssertion.assertEquals(MyAssertion.java:46)
at testcases.TestScenarios.scenarioCheckOutProcess(TestScenarios.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- scenarioCheckOutProcess -->
  <system-out/>
  <testcase classname="testcases.TestScenarios" name="scenarioValidateSortBy" time="16.895"/>
  <system-out/>
  <testcase classname="testcases.TestScenarios" name="scenarioCompareList" time="35.185"/>
  <system-out/>
  <testcase classname="testcases.TestScenarios" name="scenarioReviewValidation" time="62.978"/>
  <system-out/>
  <testcase classname="testcases.TestScenarios" name="scenarioWishList" time="48.820"/>
  <system-out/>
</testsuite> <!-- testcases.TestScenarios -->
